// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBERFem7F9uVSTCMGaMqyVV4mejH53zPjU',
    appId: '1:728926389373:web:4421f31d7002ca663f5d14',
    messagingSenderId: '728926389373',
    projectId: 'freshcuts-ad178',
    authDomain: 'freshcuts-ad178.firebaseapp.com',
    storageBucket: 'freshcuts-ad178.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7wCd8kM7MkfsEXMobYW2JnF6MOIal2CU',
    appId: '1:728926389373:android:bce505d5d700028b3f5d14',
    messagingSenderId: '728926389373',
    projectId: 'freshcuts-ad178',
    storageBucket: 'freshcuts-ad178.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDabYLCSayOhtY85oiuXAT9v_Ts_w_t3xM',
    appId: '1:728926389373:ios:3ba44e325bdb53b33f5d14',
    messagingSenderId: '728926389373',
    projectId: 'freshcuts-ad178',
    storageBucket: 'freshcuts-ad178.firebasestorage.app',
    iosBundleId: 'com.example.freshcuts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDabYLCSayOhtY85oiuXAT9v_Ts_w_t3xM',
    appId: '1:728926389373:ios:3ba44e325bdb53b33f5d14',
    messagingSenderId: '728926389373',
    projectId: 'freshcuts-ad178',
    storageBucket: 'freshcuts-ad178.firebasestorage.app',
    iosBundleId: 'com.example.freshcuts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBERFem7F9uVSTCMGaMqyVV4mejH53zPjU',
    appId: '1:728926389373:web:2f6731330ea91ab13f5d14',
    messagingSenderId: '728926389373',
    projectId: 'freshcuts-ad178',
    authDomain: 'freshcuts-ad178.firebaseapp.com',
    storageBucket: 'freshcuts-ad178.firebasestorage.app',
  );

}